# Generated by Django 3.2.5 on 2021-07-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
